name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy repo to EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/astrivioncrm-crm"
        rsync -avz --delete ./ ubuntu@${{ secrets.EC2_HOST }}:~/astrivioncrm-crm/

    - name: SSH to EC2 and deploy
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd ~/astrivioncrm-crm
        docker-compose down
        docker-compose pull || echo "No remote images"
        docker-compose build
        docker-compose up -d
        EOF
